# Hacker Welcome Plugin

if [[ -n ${HACKER_WELCOME_LOADED:-} ]]; then
  return
fi
typeset -g HACKER_WELCOME_LOADED=1

setopt local_options no_prompt_subst
zmodload zsh/datetime 2>/dev/null

typeset -g HW_PLUGIN_FILE="${${(%):-%N}}"
typeset -g HW_PLUGIN_DIR="${HW_PLUGIN_FILE:A:h}"
typeset -g HW_PROJECT_ROOT="$HW_PLUGIN_DIR"
typeset -g HW_REFRESH_SCRIPT="$HW_PROJECT_ROOT/scripts/hacker_welcome_refresh.py"
typeset -g HW_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/hacker-welcome"
typeset -g HW_CACHE_FILE="$HW_CACHE_DIR/top5.json"
typeset -g HW_BANNER_FILE="$HW_CACHE_DIR/top5.banner"
typeset -g HW_LOG_FILE="$HW_CACHE_DIR/refresh.log"
typeset -g HW_CRON_TAG="# hacker-welcome refresh"
typeset -g HW_STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/hacker-welcome"
typeset -g HW_LAST_SHOWN_FILE="$HW_STATE_DIR/last-shown"
typeset -gi HW_STORY_COUNT=5
typeset -gi HW_SHOW_INTERVAL=$((4*60*60))
typeset -gi HW_MIN_COLUMNS=160
typeset -gi HW_SETUP_DONE=0
typeset -gr HW_FALLBACK_LINE="Hacker Welcome unavailable."

# Compose the cron command that refreshes both JSON and rendered-banner artifacts.
hw::_cron_line() {
  print -r -- "*/15 * * * * ${(q)HW_REFRESH_SCRIPT} --cache ${(q)HW_CACHE_FILE} --banner ${(q)HW_BANNER_FILE} --count ${HW_STORY_COUNT} >> ${(q)HW_LOG_FILE} 2>&1 ${HW_CRON_TAG}"
}

hw::_refresh_cache_now() {
  "$HW_REFRESH_SCRIPT" \
    --cache "$HW_CACHE_FILE" \
    --banner "$HW_BANNER_FILE" \
    --count "$HW_STORY_COUNT" \
    >> "$HW_LOG_FILE" 2>&1
}

# Install a tagged cron entry once so prompt-time code never needs network work.
hw::_install_cron_if_needed() {
  local existing line cron_status entry
  local -a cron_lines kept_lines
  existing=$(crontab -l 2>/dev/null)
  cron_status=$?
  line=$(hw::_cron_line)

  if (( cron_status == 0 )) && [[ -n $existing ]]; then
    cron_lines=(${(f)existing})
    kept_lines=()
    for entry in "${cron_lines[@]}"; do
      [[ $entry == *${HW_CRON_TAG}* ]] && continue
      kept_lines+=("$entry")
    done
    print -l -r -- "${kept_lines[@]}" "$line" | crontab -
  else
    print -r -- "$line" | crontab -
  fi
}

# Perform lightweight setup only; rendering must stay local and fast.
hw::_ensure_setup() {
  (( HW_SETUP_DONE )) && return

  mkdir -p "$HW_CACHE_DIR" 2>/dev/null
  mkdir -p "$HW_STATE_DIR" 2>/dev/null
  [[ -x $HW_REFRESH_SCRIPT ]] || chmod +x "$HW_REFRESH_SCRIPT" 2>/dev/null
  hw::_install_cron_if_needed

  HW_SETUP_DONE=1
}

hw::_banner_recently_shown() {
  local interval=$1
  (( interval > 0 )) || return 1

  local now=$EPOCHSECONDS
  local last=0

  if [[ -s $HW_LAST_SHOWN_FILE ]]; then
    local raw
    if read -r raw < "$HW_LAST_SHOWN_FILE" 2>/dev/null; then
      [[ $raw == <-> ]] && last=$raw
    fi
  elif [[ -f $HW_LAST_SHOWN_FILE ]]; then
    local mtime
    if mtime=$(command stat -f %m -- "$HW_LAST_SHOWN_FILE" 2>/dev/null); then
      last=$mtime
    elif mtime=$(command stat -c %Y -- "$HW_LAST_SHOWN_FILE" 2>/dev/null); then
      last=$mtime
    fi
  fi

  (( last > 0 )) || return 1
  local elapsed=$((now - last))
  (( elapsed < 0 )) && elapsed=0
  (( elapsed < interval ))
}

hw::_record_banner_shown() {
  local now=$EPOCHSECONDS
  mkdir -p "$HW_STATE_DIR" 2>/dev/null
  print -r -- "$now" >| "$HW_LAST_SHOWN_FILE" 2>/dev/null
}

# Load and print the pre-rendered banner artifact generated by scheduled refresh.
hw::_print_cached_banner() {
  if [[ ! -s $HW_BANNER_FILE ]]; then
    print -r -- "$HW_FALLBACK_LINE"
    return 1
  fi

  if ! command cat -- "$HW_BANNER_FILE"; then
    print -r -- "$HW_FALLBACK_LINE"
    return 1
  fi

  return 0
}

hw::print_banner() {
  [[ -o interactive ]] || return
  [[ -t 1 ]] || return
  if [[ ${PWD:A} != ${HOME:A} ]]; then
    return
  fi

  local columns
  if ! columns=$(tput cols 2>/dev/null); then
    return
  fi
  [[ $columns == <-> ]] || return
  (( columns >= HW_MIN_COLUMNS )) || return

  hw::_ensure_setup

  if hw::_banner_recently_shown $HW_SHOW_INTERVAL; then
    return
  fi

  if hw::_print_cached_banner; then
    hw::_record_banner_shown
  fi
}

hw::preview_banner() {
  hw::_print_cached_banner
}

# Force an immediate refresh + banner print from any shell location/size.
hw::hackernews() {
  hw::_ensure_setup

  if ! hw::_refresh_cache_now; then
    print -u2 -- "[hacker-welcome] Refresh failed; showing cached banner"
  fi

  hw::_print_cached_banner
}

hackernews() {
  hw::hackernews "$@"
}

autoload -Uz add-zsh-hook 2>/dev/null

hw::_print_banner_once() {
  add-zsh-hook -d precmd hw::_print_banner_once 2>/dev/null
  hw::print_banner
}

if (( ${+functions[add-zsh-hook]} )); then
  add-zsh-hook precmd hw::_print_banner_once
else
  hw::print_banner
fi
